allowBuilds:
  bufferutil: set this to true or false
  electron: set this to true or false
  esbuild: set this to true or false
  utf-8-validate: set this to true or false
ignoredBuiltDependencies:
  - bufferutil
  - electron
  - esbuild
  - utf-8-validate
